name: Deploy Supabase Project

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      
    steps:
      - uses: actions/checkout@v3
      
      - uses: supabase/setup-cli@v1
        with:
          version: latest
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Set environment
        id: set-env
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            echo "ENVIRONMENT=pro" >> $GITHUB_ENV
            echo "DB_URL=${{ secrets.DATABASE_URL_PRO }}" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=stg" >> $GITHUB_ENV
            echo "DB_URL=${{ secrets.DATABASE_URL_STG }}" >> $GITHUB_ENV
          fi
          
      - name: Run database migrations
        run: |
          echo "DATABASE_URL=${{ env.DB_URL }}" > .env
          npx prisma migrate deploy
          
      - name: Deploy Edge Functions
        run: |
          supabase functions deploy --project-ref ${{ env.PROJECT_ID }}
          
      - name: Deploy Storage configuration
        run: |
          supabase db push 